<?php
/** @var $this Lib\Design\Renderer */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title><?php echo $this->getData('title'); ?></title>
    <link href="http://yui.yahooapis.com/3.5.0/build/cssreset/cssreset-min.css" media="screen" rel="stylesheet"
          type="text/css">
    <link href="http://yui.yahooapis.com/3.5.0/build/cssbase/cssbase-min.css" media="screen" rel="stylesheet"
          type="text/css">
    <link href="http://yui.yahooapis.com/3.5.0/build/cssfonts/cssfonts-min.css" media="screen" rel="stylesheet"
          type="text/css">
    <link href="<?php echo $this->getLinkUrl('skin/css/styles.css'); ?>"
          media="screen" rel="stylesheet" type="text/css">
</head>
<body>
<div class="container container_12">
    <?php echo $this->getChildHtml('header'); ?>
    <?php echo $this->getChildHtml('message'); ?>
    <div class="content"><?php echo $this->getChildHtml('content'); ?></div>
</div>
</body>
</html>
