<?php
/** @var $this \Lib\Design\Message */
$messages = $this->getMessages();
if ($messages) :
?>
<div class="alert-block grid_12">
    <?php

    while (current($messages)) :
        $item = current($messages);
        $message = $item['message'];
        $type = $item['type'];
        ?>
        <div class="alert alert-<?php echo $type ?>">
            <?php if (false !== strpos($message, 'EXCEPTION:')): ?>
                <pre><?php echo $message; ?></pre>
            <?php else: ?>
                <?php echo $message; ?>
            <?php endif; ?>
        </div>
        <?php
        next($messages);
    endwhile;
    $this->cleanUpMessages();
    ?>
</div>
<?php
endif;
