<?php /** @var $this \Jigit\Block\Main */ ?>
<div class="container container_12">
    <?php
    echo $this->getChildHtml('header');
    echo $this->getLayout()->getBlock('message')->toHtml();
    echo $this->getChildHtml('panel');
    ?>
    <div id="main_layout"></div>
</div>
<script type="text/javascript" charset="utf-8">
    (function () {
        var layout = <?php echo json_encode($this->loadConfig()); ?>;
        layout.container = 'main_layout';
        webix.ui(layout);
    }());
</script>
