<?php /** @var $this \Jigit\Block\Main */ ?>
<div class="container container_12">
    <?php echo $this->getChildHtml('header'); ?>
    <?php echo $this->getLayout()->getBlock('message')->toHtml(); ?>
    <?php echo $this->getChildHtml('panel'); ?>
    <div id="main_layout"></div>
</div>
<script type="text/javascript" charset="utf-8">
    (function () {
        var layout = <?php echo json_encode($this->loadConfig()); ?>;
        layout.container = 'main_layout';
        webix.ui(layout);
    }());
</script>
<div id="jigit_script" style="display: none"></div>
