<?php /** @var $this \Lib\Design\Renderer */ ?>
<script type='text/javascript' charset='utf-8'>
    $$('left').addView({
        view:'form',
        id:'login_form',
        width: 200,
        elements:[
            { view:'text', placeholder:'Email'},
            { view:'text', type:'password', placeholder:'Password'},
            { view:'button', value:'Login' , type: 'form' }
        ]
    });
</script>
