<?php /** @var $this Jigit\Block\Panel */
$this->setData('height', 30);
$this->setData('margin', 2);
$this->setData('padding', 5);
?>
<script type="text/javascript">
    webix.ready(function () {
        var form = $$('jigit_panel');

        //process choosing action
        form.elements.action.attachEvent('onChange', function (value) {
            if ('report' === value) {
                form.elements.top.enable();
                form.elements.low.enable();
                form.elements.ver.enable();
            } else if ('push-tasks' === value) {
                form.elements.top.disable();
                form.elements.low.disable();
                form.elements.ver.disable();
            }
        });

        form.elements.project.attachEvent('onChange', function (value) {
            webix.ajax().post(
                '<?php echo $this->getUrl('*/*/getPanelOptions'); ?>',
                form.getValues({disabled: false}), [
                    JIGIT.Form.defaultRequestCallback,
                    function (text, xml, xhr) {
                        var response = xml.json();
                        if (!response.has_errors && typeof response.data.options.data != 'undefined') {
                            form.elements.low.define(
                                'options',
                                response.data.options.data.low
                            );
                            form.elements.top.define(
                                'options',
                                response.data.options.data.top
                            );
                            form.elements.ver.define(
                                'options',
                                response.data.options.data.ver
                            );
                            console.info('Success');
                        }
                    }
                ]
            );
        });

        //process form send
        form.elements.button_submit.attachEvent('onItemClick', function () {
            var values = form.getValues({disabled: false});
            if (!form.validate()) {
                JIGIT.Form.showInvalidFormMessage();
                return;
            }
            if (values.action == 'report') {
                webix.ajax().post(
                    '<?php echo $this->getUrl('*/*/getPanelOptions'); ?>',
                    values, [
                        JIGIT.Form.defaultRequestCallback,
                        function (text, xml, xhr) {
                            var response = xml.json();
                            if (!response.has_errors) {
                                console.info('Success');
                            }
                        }
                    ]
                );
                return;
            }

            //make request
            webix.ajax().post(
                '<?php echo $this->getUrl('*/*/post'); ?>',
                values, [
                    JIGIT.Form.defaultRequestCallback,
                    function (text, xml, xhr) {
                        var response = xml.json();
                        if (!response.has_errors) {
                            console.info('Success');
                        }
                    }
                ]
            );
        });
    });
</script>
