<?php /** @var $this Jigit\Block\Panel */
$this->setData('height', 30);
$this->setData('margin', 2);
$this->setData('padding', 5);
?>
<script type="text/javascript">
    webix.ready(function () {
        var form = $$('jigit_panel');
        form.elements.button_submit.attachEvent('onItemClick', function () {
            webix.ajax().post('<?php echo $this->getUrl('*/*/post'); ?>',
                form.getValues({disabled: false}),
                [
                    JIGIT.Form.defaultRequestCallback,
                    function (text, xml, xhr) {
                        var response = xml.json();
                        if (!response.has_errors) {
                            console.info('Success');
                        }
                    }
                ]
            );
        });
    });
</script>
