<?php /** @var $this Jigit\Block\Panel */
$this->setData('height', 30);
$this->setData('margin', 2);
$this->setData('padding', 5);
?>
<script type="text/javascript">
    webix.ready(function () {
        var form = $$('jigit_panel');
        JIGIT.Panel.form = form;

        //process choosing action
        form.elements.action.attachEvent('onChange', function (value) {
            if ('report' === value) {
                form.elements.top.enable();
                form.elements.low.enable();
                form.elements.ver.enable();
            } else if ('push-tasks' === value) {
                form.elements.top.disable();
                form.elements.low.disable();
                form.elements.ver.disable();
            }
        });

        //enable fetch remote if project set
        if (form.elements.project.getValue()) {
            form.elements.fetch_remote.enable();
        }

        //change project
        form.elements.project.attachEvent('onChange', function (value) {
            if (!value) {
                return;
            }
            form.elements.fetch_remote.enable();
            webix.ajax().post(
                '<?php echo $this->getUrl('*/*/getPanelOptions'); ?>',
                form.getValues({disabled: false}), [
                    JIGIT.Form.defaultRequestCallback,
                    function (text, xml, xhr) {
                        var response = xml.json();
                        if (!response.has_errors && typeof response.data.options.data != 'undefined') {
                            JIGIT.Panel.setOptions(response.data.options.data);
                            console.info('Success');
                        }
                    }
                ]
            );
        });

        //refresh options
        form.elements.fetch_remote.attachEvent('onItemClick', function (value) {
            webix.ajax().post(
                '<?php echo $this->getUrl('*/*/getPanelOptions', array('fetch' => 1)); ?>',
                form.getValues({disabled: false}), [
                    JIGIT.Form.defaultRequestCallback,
                    function (text, xml, xhr) {
                        var response = xml.json();
                        if (!response.has_errors && typeof response.data.options.data != 'undefined') {
                            JIGIT.Panel.setOptions(response.data.options.data);
                            console.info('Success Fetch');
                        }
                    }
                ]
            );
        });

        //process form send
        form.elements.button_submit.attachEvent('onItemClick', function () {
            var values = form.getValues({disabled: false});
            if (!form.validate()) {
                JIGIT.Form.showInvalidFormMessage();
                return;
            }
            if (values.action == 'report') {
                webix.ajax().post(
                    '<?php echo $this->getUrl('*/*/getPanelOptions'); ?>',
                    values, [
                        JIGIT.Form.defaultRequestCallback,
                        function (text, xml, xhr) {
                            var response = xml.json();
                            if (!response.has_errors) {
                                console.info('Success');
                            }
                        }
                    ]
                );
                return;
            }

            //make request
            webix.ajax().post(
                '<?php echo $this->getUrl('*/*/post'); ?>',
                values, [
                    JIGIT.Form.defaultRequestCallback,
                    function (text, xml, xhr) {
                        var response = xml.json();
                        if (!response.has_errors) {
                            //TODO process response
                            console.info('Success');
                        }
                    }
                ]
            );
        });
    });
</script>
