app:
  version: 0.7.0
  config_files:
    base_dir: config
    # Project directory in base_dir. It should contain files with project specifi config
    project_dir: project
    # File with local settings. It should contain JIRA URL and JIRA username
    local: local.yml

  query:
    # Set following query parameters into config by xpath from value
    params_map:
      low: app/git/branch_low
      top: app/git/branch_top
      ver: app/jira/jql/alias/target_fix_version
      i: app/jira/jql/alias/target_fix_version_in_progress
      force-remote: app/vcs/remote/force_using
      debug: app/debug_mode

  #Config for branches and versions in VCS
  vcs:
    remote:
      #use remote repository name to identify branch when it does not exist locally
      name: origin
      #force using remote name (usually it has name "origin") even local branch does exist
      force_using: 0
    branch:
      master: master
      develop: develop
      hotfix: hotfix/%s
      release: release/%s
    version:
      prefix: v
      prefix_in_branch:

      #veresion alias for branch (fixVersion=>branch, e.g.: someFixVersion=>custom-branch)
      alias:
        v.develop:
          branch_top: develop
          branch_low: master

    #TODO Implement using git flow settings
    git_flow:
      hotfix: hotfix/
      release: release/
      develop: develop
      master: master

  jira:
    #JQLs list grouped by action
    jql:
      action:
        #General report action to identify "problem" issues
        report:
          inBranchWithoutFixVersion:
            in_progress: -1
            message: Has no fix version.
            jql: |
              project = %project%
                  AND (
                      (fixVersion != %target_fix_version% OR fixVersion is EMPTY)
                      AND status NOT IN (Open, Reopened, 'In Progress')
                  )
                  AND (
                      (key IN (%vcs_keys%) AND type NOT IN ('Sub-Task Task'))
                      OR
                      (issueFunction IN parentsOf(""project = %project% AND key IN (%vcs_keys%)""))
                  )
          notAffectsCodeWithFixVersion:
            in_progress: -1
            message: Issues which did not affect the code.
            jql: |
              project = %project%
              AND fixVersion = %target_fix_version%
              AND key NOT IN (%vcs_keys%)
              AND resolution NOT IN (%not_affects_code_resolutions%)
              AND (labels NOT IN (%not_affects_code_labels%) OR labels IS EMPTY)
              AND type NOT IN ('Change Request', Story, Epic)","Issues which did not affect the code.
          parentIssueHasCommit:
            in_progress: -1
            message: Parent issue has commit.
            jql: |
              project = %project%
                  AND fixVersion = %target_fix_version%
                  AND key IN (%vcs_keys%)
                  AND (type IN ('Change Request', Story, Epic) OR and issueFunction IN hasSubtasks())
          openWithFixVersion:
            in_progress: 1
            message: Open issues for "in progress" fix version.
            jql: |
              project = %project%
              AND status in (Open, Reopened, 'In Progress')
              AND fixVersion = %target_fix_version%
          openSubIssueInResolvedIssue:
            in_progress: 1
            message: Open TOP issues for "in progress" fix version.
            jql: |
              project = %project%
              AND status in (Open, Reopened, 'In Progress')
              AND issueFunction IN parentsOf(
                  "project = %project% AND status NOT IN (Open, Reopened, 'In Progress') AND key IN (%vcs_keys%)"
              )
          inBranchWithoutAffectedVersion:
            in_progress: 0
            message: Parent issue has commit.
            jql: |

          notInSprint:
            in_progress: 1
            message: Parent issue has commit.
            jql: |

        #"push-tasks" action to check and update fixVersion
        push-tasks:
          issuesHaveNotFixVersion:
            message: Issues which must have fixVersion.
            jql: |
              project = %project%
              AND fixVersion IS EMPTY
              AND status NOT IN (Open, Reopened, 'In Progress', Closed)
              AND issueFunction NOT IN hasSubtasks()
              %top_level_issues%
              %non_dev_issue_types%
          subIssuesHaveNotFixVersion:
            message: >
              Sub-tasks which added to parent which in a released version.
              They must have fixVersion or have to pushed to proper status.
            jql: |
              project = %project%
              AND issueFunction IN subtasksOf(
                'project = %project%
                AND fixVersion not in (EMPTY)
                AND fixVersion in releasedVersions()
                %default_quoted%'
              )
              AND fixVersion IS EMPTY
              %status_not_done%
              %non_dev_issue_types%

      #JQL aliases which might be used in JQL.
      #To use any alias just put it into JQL and wrap with %.
      #E.g: %fix_version_released%
      #Also you may use quoted alias version with suffix "_quoted" in sub-query for example.
      #E.g.: %default_quoted%
      alias:
        #This is a default JQL alias and will be added authomatically
        default: >
          AND (issuetype != Epic AND 'Epic Link' is EMPTY)
        fix_version_released: >
          AND fixversion in releasedVersions()
        fix_version_unreleased: >
          AND fixversion in unreleasedVersions()
        status_not_done: >
          AND status IN (Open, Reopened, 'In Progress', Resolved, 'Review in Progress', Reviewed)
        top_level_issues: >
          AND type NOT IN ('Sub-Task Task', 'Sub-Task Technical task')
        non_dev_issue_types: >
          AND type NOT IN ('Sub-Task Question', Question, Issue, Risk, Test)
        not_affects_code_resolutions: >
          Cancelled, 'Cannot Reproduce', Declined, Duplicate, 'Not a Bug', 'Not Actual'
        not_affects_code_labels: >
          nocode, fixedIn
