app:
  version: 0.7.0
  config_files:
    base_dir: config
    # Project directory in base_dir. It should contain files with project specifi config
    project_dir: project
    # File with local settings. It should contain JIRA URL and JIRA username
    local: local.yml

  query:
    # Set following query parameters into config by xpath from value
    params_map:
      low: app/git/branch_low
      top: app/git/branch_top
      ver: app/jira/jql/alias/version
      in-progress: app/jira/jql/alias/version_in_progress
      i: app/jira/jql/alias/version_in_progress #alias
      force-remote: app/vcs/remote/force_using
      r: app/vcs/remote/force_using #alias
      debug: app/debug_mode
      d: app/debug_mode #alias
      filter: app/jira/jql/filter_jql
      f: app/jira/jql/filter_jql #alias
      bad-commit: app/vcs/bad_commit_check
      c: app/vcs/bad_commit_check #alias
      simple-view: app/jira/issue/simple_view
      s: app/jira/issue/simple_view #alias

  #Config for branches and versions in VCS
  vcs:
    bad_commit_check: 1
    remote:
      #use remote repository name to identify branch when it does not exist locally
      name: origin
      #force using remote name (usually it has name "origin") even local branch does exist
      force_using: 0
    branch:
      master: master
      develop: develop
      hotfix: hotfix/%s
      release: release/%s
    version:
      prefix: v
      prefix_in_branch:

      #veresion alias for branch (fixVersion=>branch, e.g.: someFixVersion=>custom-branch)
      alias:
        v.develop:
          branch_top: develop
          branch_low: master

    #TODO Implement using git flow settings
    git_flow:
      hotfix: hotfix/
      release: release/
      develop: develop
      master: master

  jira:
    issue:
      simple_view: 0  #if TRUE it will present simple issue output block
      use_fields_list: 1
      fields:
      #Following queries will be used to make query
        - summary
        - assignee
        - reporter
        - versions            #affectedVersion
        - fixVersions         #fixVersion
        - changelog           #Change Log list
        - issuetype           #Issue Type
        - labels              #Labels
        - status              #Issue Status
        - customfield_10600   #Sprint IDs
    jql:
    #JQLs list grouped by action
      action:
        #General report action to identify "problem" issues
        report:
          relasedIssuesMissedFixVersion:
            # Check released fix/affects version
            in_progress: -1
            message: Issues have missed fixVersion (for resolved) or affectedVersion (for reopened)
            jql: |
              project = HAS
                AND (
                  key IN (%vcs_keys%) AND type NOT IN (%subtask_types%)
                  AND (fixVersion is EMPTY OR fixVersion != %version%)
                  AND (affectedVersion != %version% OR affectedVersion is EMPTY)
                  OR
                  key IN (%vcs_keys%) AND type IN (%subtask_types%)
                  AND (affectedVersion != %version% OR fixVersion != %version%)
                  OR
                  issueFunction IN parentsOf(
                    "project = %project%
                    AND key IN (%vcs_keys%)
                    AND (fixVersion is EMPTY OR affectedVersion is EMPTY)"
                  )
                  AND (fixVersion is EMPTY OR fixVersion != %version%)
                  AND (affectedVersion != %version% OR affectedVersion is EMPTY)
                )

          notAffectsCodeWithFixVersion:
            # Get issues which don't affect code
            helper: notAffectsCode
            in_progress: -1
            message: Issues which don't affect the code.
            jql: |
              project = %project%
              AND (fixVersion = %version% OR affectedVersion = %version%)
              AND key NOT IN (%vcs_keys%)
              AND resolution NOT IN (%not_affects_code_resolutions%)
              AND (labels NOT IN (%not_affects_code_labels%) OR labels IS EMPTY)
              AND (
                issueFunction NOT IN hasSubtasks()
                OR
                issueFunction IN subtasksOf(
                  "project = %project% AND (fixVersion = %version% OR affectedVersion = %version%)"
                )
              )
          parentIssueHasCommit:
            #Check out issues which has commits and subtasks
            in_progress: -1
            message: Parent issue has commit.
            jql: |
              project = %project%
                  AND key IN (%vcs_keys%)
                  AND issueFunction IN hasSubtasks()
          openWithFixVersion:
            in_progress: 1
            message: Open issues for "in progress" fix version.
            jql: |
              project = %project%
              AND (
                  status in (%status_open%)
                  AND fixVersion = %version%
                OR
                  status in (%status_open%)
                  AND issueFunction IN subtasksOf(
                    "project = %project% AND status NOT IN (%status_open%) AND fixVersion = %version%"
                  )
                )
          openSubIssueInResolvedIssue:
            in_progress: 1
            message: Open TOP issues for "in progress" fix version.
            jql: |
              project = %project%
              AND status in (%status_open%)
              AND issueFunction IN parentsOf(
                  "project = %project% AND status NOT IN (%status_open%) AND key IN (%vcs_keys%)"
              )
          notInSprint:
            in_progress: 1
            message: Issues not in sprint.
            jql: |
              project = %project%
              AND key IN (%vcs_keys%)
              AND (Sprint NOT IN (%active_sprints%) OR Sprint IS EMPTY)
        push-tasks: #"push-tasks" action to check and update fixVersion
          issuesHaveNotFixVersion:
            helper: missedFixVersion
            message: Issues which must have fixVersion.
            jql: |
              project = %project%
              AND fixVersion IS EMPTY
              AND status NOT IN (%status_open%, Closed)
              AND issueFunction NOT IN hasSubtasks()
              AND type NOT IN (%subtask_types%)
              AND type NOT IN (%non_dev_issue_types%)
          subIssuesHaveNotFixVersion:
#            TODO implement using affectedVersion in making report.
            helper: missedFixVersion
            message: >
              Sub-tasks which added to parent which in a released version.
              They must have fixVersion or have to pushed to proper status.
            jql: |
              project = %project%
              AND issueFunction IN subtasksOf(
                'project = %project%
                AND fixVersion not in (EMPTY)
                AND fixVersion in releasedVersions()
                AND %default_quoted%'
              )
              AND fixVersion IS EMPTY
              AND status IN (%status_open%, %status_resolved%, Closed)
              AND type IN (%non_dev_issue_types%)

      #JQL aliases which might be used in JQL.
      #To use any alias just put it into JQL and wrap with %.
      #E.g: %fix_version_released%
      #Also you may use quoted alias version with suffix "_quoted" in sub-query for example.
      #E.g.: %default_quoted%
      alias:
        #This is a default JQL alias and will be added authomatically
        default: >
          issuetype != Epic
        fix_version_released: >
          AND fixVersion in releasedVersions()
        fix_version_unreleased: >
          AND fixVersion in unreleasedVersions()
        status_open: >
          Open, Reopened, 'In Progress'
        status_resolved: >
          Resolved, 'Review in Progress', Reviewed
        subtask_types: >
          'Sub-Task Task', 'Sub-Task Technical task'
        parent_issue_types: >
          Story
        non_dev_issue_types: >
          'Sub-Task Question', Question, Issue, Risk, Test
        not_affects_code_resolutions: >
          Cancelled, 'Cannot Reproduce', Declined, Duplicate, 'Not a Bug', 'Not Actual'
        not_affects_code_labels: >
          nocode, fixedIn
